# Generated by Django 3.2.9 on 2022-01-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='type',
            new_name='game_type',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='created_by',
            new_name='gamer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_limit',
            new_name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_on',
        ),
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='Hasbro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
