# Generated by Django 3.2.9 on 2022-01-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20220105_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametype',
            old_name='title',
            new_name='label',
        ),
    ]
